"""Add detailed address fields

Revision ID: 40cf4add34a6
Revises: b6bd7f7d8e8b
Create Date: 2026-05-05 13:14:50.892109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cf4add34a6'
down_revision: Union[str, Sequence[str], None] = 'b6bd7f7d8e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fretes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))
        batch_op.alter_column('destino',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fretes', 'destino',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('fretes', 'numero')
    op.drop_column('fretes', 'logradouro')
    op.drop_column('fretes', 'bairro')
    op.drop_column('fretes', 'cidade')
    op.drop_column('fretes', 'estado')
    op.drop_column('fretes', 'cep')
    # ### end Alembic commands ###
